# ================= GLOBAL SETTINGS =================
server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: inclusion-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # puede ser: local, docker, prod

  jackson:
    time-zone: UTC
    serialization:
      INDENT_OUTPUT: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:inclusion_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:root}:${MONGO_INITDB_ROOT_PASSWORD:example}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_INITDB_DATABASE:inclusion_db}?authSource=admin

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:clave-muy-segura-para-jwt-que-debe-ser-larga}
  expirationMs: ${JWT_EXPIRATION_MS:86400000} # 1 día

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO

# ================= LOCAL PROFILE =================
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:inclusion_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  data:
    mongodb:
      uri: mongodb://localhost:27017/${MONGO_INITDB_DATABASE:inclusion_db}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# ================= DOCKER PROFILE =================
---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://${DB_HOST:pg_inclusion}:${DB_PORT:5432}/${POSTGRES_DB:inclusion_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST:mongo_inclusion}:${MONGO_PORT:27017}/${MONGO_INITDB_DATABASE}?authSource=admin

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
